//autogenerated:yes
//nolint:revive,lll
package mower_map

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "github.com/bluenviron/goroslib/v2/pkg/msgs/geometry_msgs"
)


type MapArea struct {
    msg.Package         `ros:"mower_map"`
    Name                string
    Active              bool
    Area                geometry_msgs.Polygon
    Obstacles           []geometry_msgs.Polygon
    Angle               float64
    OutlineCount        int32   `rosname:"outline_count"`
    OutlineOverlapCount int32   `rosname:"outline_overlap_count"`
    OutlineOffset       float64 `rosname:"outline_offset"`
}
